name: Theneo API Documentation
description: Generate Stripe-like API Documentation
inputs:
  PATH:
    description: "../../doc/api.yml"
    required: true
  PROJECT_KEY:
    description: "aa98a56c-e011-464e-8999-d4cd516b54c8"
    required: true
  SECRET:
    description: "secret"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "book-open"
  color: "orange"