name: Theneo API Documentation
on:
  push:
    branches:
      - main
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: "16"
      - name: Theneo API Documentation
        uses: Theneo-Inc/api-documentation@1.0
        with:
          PATH: ../../doc/4.json
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          SECRET: ${{ secrets.TEST_API_KEY }}

