name: Update documention
on:
  pull_request:
    branches:
      - main
jobs:
  update-doc:
    name: update theneo doc
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: process documentation on server
        uses: theneoAPIDoc/api-documentation@main
        with:
          PATH: 4.json
          PROJECT_KEY: "aa98a56c-e011-464e-8999-d4cd516b54c8"
          SECRET: ${{TEST_API_KEY}}